### ISSUE TITLE
Rewrite Lexer

### ISSUE THREAD

**Issue by Plasma3** [Plasma3/Calculator#4]
# Tasks
- [x] Update Token to specs
- [x] Update TokenKind to specs
- [x] Update Location to specs
- [x] Add doc for Errors
- [x] Update Errors to specs
- [x] Imlement Lexer
   - [-] Function lex_file // Let's not do this one
   - [x] Function lex_string
   - [x] Function lex_line
- [x] Create Gitgraph with mermaid
- [x] Create Class Diagram over Lexer with mermaid

## Specs
Available in [docs](https://github.com/Plasma3/Calculator/blob/lexer-rewrite/docs/lexer_design.md)

**Comment by Plasma3** [comment]
Fixed with #8
