### ISSUE TITLE
Parser

### ISSUE THREAD

**Issue by Plasma3** [Plasma3/Calculator#7]
# Tasks
- [ ] Remove old classes
- [ ] Add unary operation
- [ ] Add binary operation
- [ ] Add comunativ operation
- [ ] Sketch out parser outline
- [ ] Add doc for support classes
- [ ] Add doc for parser
- [ ] Implement parser
- [ ] Update specs down below

## Specs
Available in [docs](https://github.com/Plasma3/Calculator/blob/lexer-rewrite/docs/lexer_design.md)
